- id: '1720792091613'
  alias: Paul's office plug on when motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 5ec32a090c07903d720c443932cf7d28
    entity_id: f954ba669b10dc5f70284252ec5a435d
    domain: binary_sensor
  condition:
  - condition: state
    state: home
    entity_id: device_tracker.iphone
  - condition: time
    after: 08:00:00
    before: '23:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pauls_office
  mode: single
- id: '1720792138608'
  alias: Paul's office plug off when no motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 5ec32a090c07903d720c443932cf7d28
    entity_id: f954ba669b10dc5f70284252ec5a435d
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pauls_office
  mode: single
- id: '1721266883410'
  alias: Kitchen Island lights on for evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      kelvin: 4000
      brightness_pct: 100
    target:
      entity_id: light.kitchen_island
  mode: single
- id: '1721266959801'
  alias: 'Kitchen Island lights off at night '
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.kitchen_island
    data:
      transition: 300
  mode: single
- id: '1721267166912'
  alias: Kitchen Island lights dim at 2130
  description: ''
  trigger:
  - platform: time
    at: '21:30:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_island
    data:
      transition: 300
      kelvin: 3000
      brightness_pct: 50
  mode: single
- id: '1721268127220'
  alias: Hutch on for evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.hutch
  mode: single
- id: '1721268165405'
  alias: Hutch off at night
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.hutch
  mode: single
- id: '1721268548576'
  alias: Front Lights on for evening
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.front_lights
  mode: single
- id: '1721268654637'
  alias: Front Lights dim at 2130
  description: ''
  trigger:
  - platform: time
    at: '21:30:00'
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 15
    target:
      entity_id: light.front_lights
  mode: single
- id: '1721268714482'
  alias: Front Lights off at 2300
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.front_lights
  mode: single
- id: '1721269179018'
  alias: Garage Left offline notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.garage_left
    to: unavailable
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_pauls_iphone
    metadata: {}
    data:
      message: Garage left light is unavailable.
      title: Light offline
  mode: single
- id: '1721269368715'
  alias: Garage Left online notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.garage_left
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to:
    from: unavailable
  condition: []
  action:
  - service: notify.mobile_app_pauls_iphone
    metadata: {}
    data:
      message: Garage left light is back online.
      title: Light online
  mode: single
- id: '1721271453963'
  alias: Kitchen Island lights dim at 2300
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_island
    data:
      transition: 300
      kelvin: 2000
      brightness_pct: 25
  mode: single
- id: '1721346844039'
  alias: Kitchen Island - Adjust color temp for daytime
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.kitchen_island
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    before: sunset
    before_offset: -00:30:00
    after: sunrise
    after_offset: 00:30:00
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
      kelvin: 4000
    target:
      entity_id: light.kitchen_island
  mode: single
- id: '1721348824948'
  alias: Master Bedroom - Adjust color temp for daytime
  description: ''
  triggers:
  - entity_id:
    - light.master_bedroom
    from: 'off'
    to: 'on'
    trigger: state
  conditions:
  - condition: sun
    before: sunset
    before_offset: -00:30:00
    after: sunrise
    after_offset: 00:30:00
  actions:
  - metadata: {}
    data:
      brightness_pct: 100
      kelvin: 4000
    target:
      entity_id: light.master_bedroom
    action: light.turn_on
  mode: single
- id: '1721348927268'
  alias: Master Bedroom - Adjust color temp for evening
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.master_bedroom
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    before_offset: 00:30:00
    after: sunset
    after_offset: -00:30:00
  action:
  - service: light.turn_on
    metadata: {}
    data:
      kelvin: 3000
      brightness_pct: 50
    target:
      entity_id: light.master_bedroom
  mode: single
- id: '1733093505530'
  alias: Christmas lights on
  description: ''
  triggers:
  - event: sunset
    offset: -00:30:00
    trigger: sun
  conditions: []
  actions:
  - metadata: {}
    data: {}
    action: switch.turn_on
    target:
      entity_id: switch.pauls_office
  mode: single
- id: '1733093539161'
  alias: Christmas lights off
  description: ''
  triggers:
  - at: '23:00:00'
    trigger: time
  conditions: []
  actions:
  - metadata: {}
    data: {}
    action: switch.turn_off
    target:
      entity_id: switch.pauls_office
  mode: single
- id: '1743618572576'
  alias: 'Living room motion '
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.amcrest_ip4m_1041b_amc058e8_ce1851_motion
    for:
      hours: 0
      minutes: 0
      seconds: 3
    trigger: state
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - metadata: {}
    data:
      message: Motion detected in the Living Room
      title: Living Room
    action: notify.mobile_app_pauls_iphone
  mode: single
- id: '1743638555738'
  alias: Front Door motion
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.front_door_person_occupancy
    for:
      hours: 0
      minutes: 0
      seconds: 3
    trigger: state
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - metadata: {}
    data:
      message: Person detected at the Front Door
      title: Front Door
    action: notify.mobile_app_pauls_iphone
  mode: single
- id: '1743965005710'
  alias: Living Room Recording OFF Geofence
  description: ''
  triggers:
  - device_id: cd012e2e728ee85536bdeb80999436eb
    domain: device_tracker
    entity_id: d17286835af72954f423552db3b0d408
    type: enters
    trigger: device
    zone: zone.home
  - device_id: d66e6b56180084960e83b4b19a5e2db9
    domain: device_tracker
    entity_id: f02ba763297f57cf504c27b2b89ca20c
    type: enters
    trigger: device
    zone: zone.home
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_recordings
  mode: single
- id: '1743965269020'
  alias: Living Room Recording ON Geofence
  description: ''
  triggers:
  - device_id: cd012e2e728ee85536bdeb80999436eb
    domain: device_tracker
    entity_id: d17286835af72954f423552db3b0d408
    type: leaves
    trigger: device
    zone: zone.home
  conditions:
  - condition: device
    device_id: d66e6b56180084960e83b4b19a5e2db9
    domain: device_tracker
    entity_id: f02ba763297f57cf504c27b2b89ca20c
    type: is_not_home
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.living_room_recordings
  mode: single
- id: '1743966695398'
  alias: Front Door Motion Notification
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      presence_filter: []
      camera:
      - camera.front_door
      notify_device: cd012e2e728ee85536bdeb80999436eb
      message: A Person was detected at the Front Door.
      title: Front Door
      critical: 'false'
      video: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      final_update: true
      base_url: https://homeassistant.lpgrossi18.duckdns.org
      debug: true
      ios_live_view: camera.front_door
      zones: []
      zone_filter: false
      url_1: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      master_condition: []
      review_severity:
      - alert
      - detection
      url_2: '{{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json[''after''][''camera'']
        | lower | replace(''-'',''_'')}}?token={{state_attr( ''camera.'' ~ camera,
        ''access_token'')}}'
- id: '1743968789389'
  alias: Living Room Motion Notification
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      presence_filter:
      - device_tracker.iphone
      - device_tracker.lisa_grossis_iphone
      camera:
      - camera.living_room
      notify_device: cd012e2e728ee85536bdeb80999436eb
      message: Motion detected in the Living Room
      title: Living Room
      critical: 'false'
      video: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      final_update: true
      base_url: https://homeassistant.lpgrossi18.duckdns.org
      debug: true
      ios_live_view: camera.living_room
      zones:
      - porch
      zone_filter: false
      url_1: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      review_severity:
      - alert
