- id: '1721271306107'
  name: New scene
  entities:
    light.master_bedroom:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      supported_color_modes:
      - color_temp
      - xy
      effect: None
      color_mode: color_temp
      brightness: 63
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      mode: normal
      dynamics: none
      friendly_name: Master Bedroom
      supported_features: 44
      state: 'on'
  metadata: {}
