mqtt:
  host: 192.168.1.100
  user: homeassistant
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg: # For AMD GPU, set container environment variable LIBVA_DRIVER_NAME=radeonsi
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p # Intel-based CPUs (<10th Generation) via Quicksync
  # hwaccel_args: preset-vaapi

cameras:
  Backyard_Floodlight:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.21/
          roles:
            - detect
            - record
            # - rtmp
    # rtmp:
    #   enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920
      height: 1080
  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.22/
          roles:
            - detect
            - record
            # - rtmp
    # rtmp:
    #   enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 2560
      height: 1440

objects:
  track:
    - person
    - dog
    - cat

record:
  enabled: True
  expire_interval: 60
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      default: 4
      mode: active_objects
      objects:
        dog: 2
        cat: 2

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
  required_zones: []
  retain:
    default: 14
    objects:
      dog: 2
      cat: 2

rtmp:
  enabled: False

live:
  height: 720
  # 1 is the highest quality, and 31 is the lowest.
  quality: 8

timestamp_style:
  # "tl", "tr", "bl", "br"
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"

logger:
  logs:
    frigate.mqtt: error
